title: Taylor Bryant - Front-end Developer
description: A blog about web dev tools, productivity tips, and more.

compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all

exclude:
  - .gitignore
  - README.md
  - LICENSE.md
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - node_modules
  - package.json
  - package-lock.json
  - src
  - tailwind.config.js