title: Taylor Bryant | Software Engineer
description: A blog about web dev tools, productivity tips, and more.

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all

include:
  - _redirects

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
